google_analytics:

title: Elements
description: Elements is a simple, speedy, spell-slinging party game for 2-8 players

plugins:
  - jekyll-seo-tag

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]